### ISSUE TITLE
Results in dg_mnist.py

### ISSUE THREAD

**Issue by LinkWoong** [val-iisc/deligan#4]
I've tried the mnist model. However, I only got  some noises.....any comments?
<img src="https://raw.githubusercontent.com/LinkWoong/Zeroshot-GAN/master/images/NN40000.png" >

**Comment by swami1995** [comment]
Hi, I'm sorry for taking this long to reply.
I'm frankly speaking not sure what's causing this in your case. I just ran these experiments multiple times and it is converging to produce meaningful generations. One way to test if everything at your end is working properly is to check if increasing the dataset size gradually and training produces better results. Hope that helps.
