### ISSUE TITLE
generating same sample

### ISSUE THREAD

**Issue by SchafferZhang** [val-iisc/deligan#6]
Hi, when I utilize the trained model to generate the samples, which the corresponding code is 

`#Uncomment this block for generating GAN samples from given model
'''
f = np.load(args.results_dir + '/disc_params1180.npz')
param_values = [f['arr_%d' % i] for i in range(len(f.files))]
for i,p in enumerate(disc_params):
    p.set_value(param_values[i])
print("disc_params fed")
f = np.load(args.results_dir + '/gen_params1180.npz')
param_values = [f['arr_%d' % i] for i in range(len(f.files))]
for i,p in enumerate(gen_params):
    p.set_value(param_values[i])
print("gen_params fed")
samples=[]
for i in range(50):
    sample_x = samplefun()
    samples.append(sample_x)
samples = np.concatenate(samples,0)
print(samples)
#sys.exit()
np.save(args.results_dir + '/samples50k.npy', samples)
print("samples saved")
sys.exit()
'''`

but for each iteration i, the image in the sample_x are diverse, but every sample_x is the same. what' wrong with it?

**Comment by swami1995** [comment]
Hi,
Yeah, we faced that problem too sometimes with very small datasets, but some workarounds helped us resolve those issues.. for example decreasing the dimensionality of z, increasing the number of gaussians components and increasing the weight of the regularisation term.. But I agree, even after these workarounds sometimes it still was unstable and difficult to tune. Perhaps tuning these parameters might help?
